import { useMemo } from "react";
import { Copy, FileText } from "lucide-react";
import type { GitHubRepo, GitHubUser } from "../lib/github";
import { siteMeta } from "../config/siteMeta";
import { calculateEnergyScore } from "../lib/galaxy";
import type { ThemeConfig } from "../lib/themes";

interface ReadmeGeneratorProps {
  theme: ThemeConfig;
  user: GitHubUser;
  repos: GitHubRepo[];
  onClose: () => void;
}

export function ReadmeGenerator({
  theme,
  user,
  repos,
  onClose,
}: ReadmeGeneratorProps) {
  const energy = useMemo(() => calculateEnergyScore(repos), [repos]);

  const topRepos = useMemo(
    () =>
      [...repos]
        .sort((a, b) => b.stargazers_count - a.stargazers_count)
        .slice(0, 5),
    [repos]
  );

  const totalStars = repos.reduce((s, r) => s + r.stargazers_count, 0);
  const totalForks = repos.reduce((s, r) => s + r.forks_count, 0);
  const galaxyLink = `${siteMeta.demoUrl}?user=${user.login}`;

  const markdown = `## 🌌 My Open Source Galaxy

[![Repo Galaxy Studio](${siteMeta.demoUrl}icon.svg)](${galaxyLink})

> **[${user.login}'s Galaxy](${galaxyLink})** — ${energy.emoji} ${energy.level}

### 📊 Stats

| Metric | Value |
|--------|-------|
| Repos | ${repos.length} |
| Total Stars | ${totalStars.toLocaleString()} |
| Total Forks | ${totalForks.toLocaleString()} |
| Energy Score | ${energy.score.toLocaleString()} |

### ⭐ Top Repos

${topRepos.map((r) => `- [**${r.name}**](${r.html_url}) — ⭐ ${r.stargazers_count} · ${r.language || "N/A"}${r.description ? `\n  > ${r.description}` : ""}`).join("\n")}

### 🔗 Links

- 🌌 [Explore Galaxy](${galaxyLink})
- 📦 [Repo Galaxy Studio](${siteMeta.repositoryUrl})

---
*Generated by [Repo Galaxy Studio](${siteMeta.repositoryUrl})*`;

  const copyMarkdown = () => {
    navigator.clipboard.writeText(markdown);
  };

  return (
    <div
      className="readme-generator"
      style={{ background: theme.panelBg, color: theme.text }}
      data-testid="readme-generator"
    >
      <div className="readme-header">
        <h3>
          <FileText size={16} color={theme.accent} /> README 卡片生成
        </h3>
        <button onClick={onClose} style={{ color: theme.textSecondary }} aria-label="关闭">
          ×
        </button>
      </div>

      <p style={{ color: theme.textSecondary, fontSize: "13px" }}>
        生成可嵌入 GitHub Profile README 的 Markdown 卡片。
      </p>

      <pre
        className="readme-preview"
        style={{
          background: theme.bgSecondary,
          color: theme.text,
          borderColor: theme.border,
        }}
      >
        {markdown}
      </pre>

      <button
        onClick={copyMarkdown}
        className="readme-copy-btn"
        style={{ background: theme.accent, color: "#fff" }}
        aria-label="复制 Markdown"
      >
        <Copy size={14} /> 复制 Markdown
      </button>
    </div>
  );
}
